language: node_js

node_js:
  - "node"

install:
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test

notifications:
  email: false

branches:
  only:
    - master
    - dev
